[package]
name = "launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full", "tracing"] }
console-subscriber = "0.4"
anyhow = "1.0"
nos-common = { path = "../nos-common" }
comp-bgp = { path = "../components/bgp" }
comp-rib = { path = "../components/rib" }
comp-ifmgr = { path = "../components/ifmgr" }